### PR TITLE
Multimethod

### PR DESCRIPTION
**Pull request by bbrown1229**

### CODE REVIEW

**Comment by dtolb** [comment]
Is there a way to reduce each method's min height? There is a lot of white space unused

screen shot 2017-03-21 at 16 54 57

**Comment by bbrown1229** [comment]
That should do it

**Comment by dtolb** [comment]
The `min-height` didn't get overruled (at least on my computer) From [line 57](https://github.com/Bandwidth/docs-theme/blob/multimethod/src/less/website/base.less#L57) 

screen shot 2017-03-21 at 23 33 51
screen shot 2017-03-21 at 23 34 27
screen shot 2017-03-21 at 23 35 00

Do I need to give that section another class or remove the min-height like we did in [index.js](https://github.com/Bandwidth/docs-theme/blob/multimethod/index.js#L119)

Right now the `div` has both `api-method-code` and `mm-method-code`

```
<div class="api-method-code mm-method-code">
```

**Comment by bbrown1229** [comment]
screen shot 2017-03-22 at 8 37 18 am

**Comment by bbrown1229** [comment]
It works on my screen

**Pull request merged**
